---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes  
    when: ansible_distribution in  ["Ubuntu", "Debian"]

  - name: install httpd package
    apt:
      name: httpd
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install php
    apt:
      name: php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]
