---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    dnf:
      update_cache: yes  

  - name: install httpd package
    dnf:
      name: httpd
      state: latest

  - name: install php
    dnf:
      name: php
      state: latest
