---

- hosts: all
  become: true
  tasks:

  - name: update repo
    dnf:
      update_cache: yes  

  - name: remove httpd
    dnf:
      name: httpd
      state: absent

  - name: remove php
    dnf:
      name: php
      state: absent
        
